### ISSUE TITLE
Forbidden 403 error | Logout not working.

### ISSUE THREAD

**Issue by mzaboss** [liamcottle/Snapchat-SDK-PHP#26]
Hi,

    Steps to produce error or something which is not working for me.

1. With $snapchat instance login to a account for example say 'mza'
2. Upload image or do whatever you want to do with 'mza'
3. $snapchat->logout() // This should logout 'mza'
4. login with new account say 'deep'
5. Do work with 'deep'
6. Logout from 'deep'
7. Sleep for some time say 1 hour
8. Try to login again with 'mza'
9. Now whenever trying to do anything with 'mza' I am getting error `Snapchat Request failed: [POST] [https://app.snapchat.com/bq/upload] HTTP/1.1 403 Forbidden`
I am getting the same error whenever I am trying to LOGIN AGAIN TO PREVIOUSLY LOGGED IN ACCOUNT. IMHO logout is not working correctly.

Thanks and regards,
cheers

Example: https://gist.github.com/mzaboss/5cc1f81b93f8549f1bbab7f9ba775d45

**Comment by liamcottle** [comment]
Hi Mza,

The code in your Gist file is a little difficult to follow.

However, since you're working inside of loops and making lots of login requests between different accounts, I'd suggest creating a new instance of the `CasperDeveloperAPI` and `Snapchat` classes in each loop.

There might be an issue with the instance trying to use tokens etc from the previous accounts when you do your next loop.

Just move these two lines so they're inside of your loop. (Before you make the login requests).

```php
$casper = new \Casper\Developer\CasperDeveloperAPI(API_KEY, API_SECRET);
$snapchat = new \Snapchat\Snapchat($casper);
```

That way, there shouldn't be any values floating around to cause issues.

Cheers,
Liam Cottle
