### ISSUE TITLE
Unable to login.

### ISSUE THREAD

**Issue by mzaboss** [liamcottle/Snapchat-SDK-PHP#34]
Hi,

I have account that unable to login. get no response at all.

Please advice.

thank you,
regards.

**Comment by liamcottle** [comment]
Hi, you'll need to be a little more descriptive about this.

- Which server is providing no response? Casper or Snapchat
- When you say 'no response at all', is the response body from the server blank, or is the server not responding to your request?
- If the response body is blank, what are the response headers and response code?
- Have you tried with another account? If yes, and that works, I can't really help you as it'll be an issue with the Snapchat servers, which I have no control over.

Cheers

**Comment by mzaboss** [comment]
<?php

require("../src/autoload.php");

$casper = new \Casper\Developer\CasperDeveloperAPI("", "");
$snapchat = new \Snapchat\Snapchat($casper);

try {

$login = $snapchat->login("jtttt_tourist", "a924");

$ans = $snapchat->addFriend("mzaboss");
echo $ans;

} catch(Exception $e){
    //Something went wrong...
    echo $e->getMessage() . "\n";
}


Response:
mza@m:~/1/Snapchat-SDK-PHP-master/examples$ php example.loginAndAddFriend.php
You must be logged in to call addFriend().

**Comment by liamcottle** [comment]
You'll need to proxy the server requests to see what's going on, as this doesn't really answer the above questions.

The `login` method should throw an exception if login failed, but it seems the server has just not provided all of the expected data. (I should make it throw an exception in this case, it currently doesn't)

It's likely the username didn't come back in the snapchat response, and that's why `addFriend` threw an exception.

... but you'll need to proxy the requests, as I can't reproduce this.

**Comment by liamcottle** [comment]
Just noticed you edited your comment...

Yes, that's what I mean, the code expects that the `username` and `auth_token` are provided by the server if the `status` is `0`.

Since it's zero, an exception isn't thrown. However, the code doesn't actually check that the `username` and `auth_token` are in the server response. (I should add this check, but something else is going on here).

As mentioned previously, you will need to proxy the Snapchat API requests to see what the server is returning.

I can't help you any further with this, unless you can do that.

**Comment by mrsoyer** [comment]
hey liam how are you ? 

I know that accepted no new user but might you are discussing?

**Comment by liamcottle** [comment]
Unfortunately not sorry.

**Comment by mrsoyer** [comment]
:(ok! I yet know very well your API for using it!

**Comment by mrsoyer** [comment]
and I know its price

**Comment by mrsoyer** [comment]
Hey Liam, I know very well the technical problems that you encounter, and know already very well your API, its price to have worked on it.

I would be a very nice client, which ask nothing nicely nicely in his corner :)

**Comment by mrsoyer** [comment]
i'm very sad :(

**Comment by mzaboss** [comment]
Snapchat response:

[http://imgur.com/a/vYnhg](http://imgur.com/a/vYnhg)



```
{
	"message": "You\u0027re using a version of Snapchat or operating system that\u0027s no longer supported. Please upgrade your device\u0027s operating system and update to the newest app version to use Snapchat. Thanks!",
	"logged": false
}
```

**Comment by mzaboss** [comment]
Any updates?, Thank you.

**Comment by mzaboss** [comment]
Works fine. thank you.
